/**
   USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
   OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
   THE PRODUCT.
   <p/>
   IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD B2N LTD., ITS
   RELATED COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY
   CLAIMS OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR
   DISTRIBUTION OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES
   ARISING OUT OF OR RESULTING FROM THE USE, MODIFICATION, OR
   DISTRIBUTION OF PROGRAMS OR FILES CREATED FROM, BASED ON, AND/OR
   DERIVED FROM THIS SOURCE CODE FILE.
*/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Door Lock


#define LIGHT_PIN 10

bool light_on = false;

void LIGHT_INIT()
{
  pinMode(LIGHT_PIN, OUTPUT);
}

void LIGHT_ON()
{
  digitalWrite(LIGHT_PIN, HIGH);
  
  light_on = true;
}


void LIGHT_OFF()
{
  digitalWrite(LIGHT_PIN, LOW);

  light_on = false;
}


void LIGHT_WORK()
{
  
}

bool IS_LIGHT_ON()
{
  return light_on;  
}



