/**
   USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
   OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
   THE PRODUCT.
   <p/>
   IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD B2N LTD., ITS
   RELATED COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY
   CLAIMS OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR
   DISTRIBUTION OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES
   ARISING OUT OF OR RESULTING FROM THE USE, MODIFICATION, OR
   DISTRIBUTION OF PROGRAMS OR FILES CREATED FROM, BASED ON, AND/OR
   DERIVED FROM THIS SOURCE CODE FILE.
*/

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Door Lock

//10sec
#define TIMESTAMP_TIMEOUT  1000
uint32_t TIMESTAMP_LAST_EXECUTE;
uint32_t TIMESTAMP_DIFF;
uint32_t TIMESTAMP_NOW = 0;

void TIMESTAMP_INIT()
{
  TIMESTAMP_NOW = millis();
}

void TIMESTAMP_WORK()
{
  TIMESTAMP_DIFF = ((uint32_t)(((uint32_t)millis()) - TIMESTAMP_LAST_EXECUTE));
  
  if (TIMESTAMP_DIFF >= TIMESTAMP_TIMEOUT)
  {
    TIMESTAMP_NOW = TIMESTAMP_NOW + TIMESTAMP_DIFF;
    TIMESTAMP_LAST_EXECUTE = (uint32_t)millis();
  }
}

long GET_TIMESTAMP_NOW()
{
  return TIMESTAMP_NOW;  
}



